### ISSUE TITLE
ICS OS fails to compile in the GNU C Compiler versions 5.0 and above

### ISSUE THREAD

**Issue by jkcdarunday** [srg-ics-uplb/ics-os#1]
ICS OS fails to compile in the GNU C Compiler versions 5.0 and above.

The linker seems to be unable to find references to inline functions. 

The following is the output in the terminal when running make:

```
make -C kernel/
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/skeithc/Codes/C/ics-os2/ics-os/kernel'
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o scheduler.o process/scheduler.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o fat.o filesystem/fat12.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o iso9660.o filesystem/iso9660.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o devfs.o filesystem/devfs.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o iomgr.o iomgr/iosched.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o devmgr_error.o devmgr/devmgr_error.c
gcc -m32 -w -nostdlib -fno-builtin -ffreestanding -c -o kernel32.o kernel32.c 
nasm -f elf32 -o startup.o startup/startup.asm
nasm -f elf32 -o asmlib.o startup/asmlib.asm 
startup/asmlib.asm:300: warning: label alone on a line without a colon might be in error
nasm -f elf32 -o irqwrap.o irqwrap.asm
strip --strip-debug *.o
ld -melf_i386  -T lscript.txt -Map mapfile.txt

kernel32.o: In function `ports_write':
(.text+0x16e): undefined reference to `outportw'
kernel32.o: In function `ports_read':
(.text+0x1f0): undefined reference to `inportw'
kernel32.o: In function `read_regs':
(.text+0x2e6): undefined reference to `inportb'
kernel32.o: In function `read_regs':
(.text+0x311): undefined reference to `outportb'
kernel32.o: In function `read_regs':
(.text+0x321): undefined reference to `inportb'
kernel32.o: In function `read_regs':
(.text+0x356): undefined reference to `outportb'
kernel32.o: In function `read_regs':
(.text+0x366): undefined reference to `inportb'
kernel32.o: In function `read_regs':
(.text+0x39b): undefined reference to `outportb'
...
Makefile:47: recipe for target 'Kernel32.bin' failed
make[1]: *** [Kernel32.bin] Error 1
make[1]: Leaving directory '/home/skeithc/Codes/C/ics-os2/ics-os/kernel'
Makefile:7: recipe for target 'vmdex' failed
make: *** [vmdex] Error 2
```

**Comment by jkcdarunday** [comment]
Removing all instances of the `inline` keyword seems to have fixed this. [Sources](https://en.wikipedia.org/wiki/Inline_function) on the internet do suggest to leave the inlining of functions to the compiler too.

**Comment by jachermocilla** [comment]
Use the different makefile in the kernel folder

https://github.com/srg-ics-uplb/ics-os/blob/master/ics-os/kernel/Makefile.Ubuntu_14.04_x86_64
